-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 22:44:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиент`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиент` (
  `Номер клиента` INT NOT NULL AUTO_INCREMENT,
  `Скидка` INT ZEROFILL NOT NULL,
  `Льгота` INT ZEROFILL NULL,
  PRIMARY KEY (`Номер клиента`),
  UNIQUE INDEX `Номер клиента_UNIQUE` (`Номер клиента` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Теплица`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Теплица` (
  `Номер теплицы` INT NOT NULL,
  `Климат` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Номер теплицы`),
  UNIQUE INDEX `Номер теплицы_UNIQUE` (`Номер теплицы` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Растение`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Растение` (
  `Номер растения` INT NOT NULL,
  `Зимостойкость` TINYINT(1) NOT NULL,
  `Семейство` VARCHAR(45) NOT NULL,
  `Сорт` VARCHAR(45) NOT NULL,
  `Тип почвы` VARCHAR(45) NOT NULL,
  `Жесткость побегов` VARCHAR(45) NOT NULL,
  `Густота посадки` VARCHAR(45) NOT NULL,
  `Цена растения` INT NOT NULL,
  `Цена семян` INT NOT NULL,
  PRIMARY KEY (`Номер растения`),
  INDEX `Номер растения_UNIQUE` (`Номер растения` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Экземпляр растения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Экземпляр растения` (
  `Номер экземпляра` INT NOT NULL,
  `Номер растения` INT NOT NULL,
  `Номер теплицы` INT NOT NULL,
  `Дата посева` DATE NOT NULL,
  `Дата всхода` DATE NOT NULL,
  `Форма кроны` VARCHAR(45) NOT NULL,
  `Высота растения` INT NOT NULL,
  PRIMARY KEY (`Номер экземпляра`),
  UNIQUE INDEX `Номер растения_UNIQUE` (`Номер экземпляра` ASC) VISIBLE,
  UNIQUE INDEX `Номер теплицы_UNIQUE` (`Номер теплицы` ASC) VISIBLE,
  CONSTRAINT `Номер теплицы`
    FOREIGN KEY (`Номер теплицы`)
    REFERENCES `mydb`.`Теплица` (`Номер теплицы`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Номер растения`
    FOREIGN KEY (`Номер растения`)
    REFERENCES `mydb`.`Растение` (`Номер растения`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Экземпляр купленного тоовара`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Экземпляр купленного тоовара` (
  `Купленый товар` VARCHAR(45) NOT NULL,
  `Номер экземпляра` INT NOT NULL,
  `Количество` INT NOT NULL,
  PRIMARY KEY (`Купленый товар`),
  UNIQUE INDEX `Купленый товар_UNIQUE` (`Купленый товар` ASC) VISIBLE,
  UNIQUE INDEX `Номер экземпляра_UNIQUE` (`Номер экземпляра` ASC) VISIBLE,
  CONSTRAINT `Номер экземпляра`
    FOREIGN KEY (`Номер экземпляра`)
    REFERENCES `mydb`.`Экземпляр растения` (`Номер экземпляра`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Продажа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Продажа` (
  `Номер операции` INT NOT NULL,
  `Номер клиента` INT NOT NULL,
  `Купленый товар` VARCHAR(45) NOT NULL,
  `Итоговая цена` INT NOT NULL,
  `Дата` DATE NOT NULL,
  PRIMARY KEY (`Номер операции`),
  UNIQUE INDEX `Номер операции_UNIQUE` (`Номер операции` ASC) VISIBLE,
  INDEX `Номер клиента_idx` (`Номер клиента` ASC) VISIBLE,
  UNIQUE INDEX `Номер клиента_UNIQUE` (`Номер клиента` ASC) VISIBLE,
  UNIQUE INDEX `Купленый товар_UNIQUE` (`Купленый товар` ASC) VISIBLE,
  CONSTRAINT `Номер клиента`
    FOREIGN KEY (`Номер клиента`)
    REFERENCES `mydb`.`Клиент` (`Номер клиента`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Купленый товар`
    FOREIGN KEY (`Купленый товар`)
    REFERENCES `mydb`.`Экземпляр купленного тоовара` (`Купленый товар`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
